# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{conversions}
  s.version = "1.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Manfred Stienstra"]
  s.date = %q{2009-09-15}
  s.description = %q{      A Ruby on Rails plugin that adds conversion capabilities to numeric objects"
}
  s.email = %q{manfred@fngtps.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README",
     "Rakefile",
     "TODO",
     "VERSION.yml",
     "conversions.gemspec",
     "init.rb",
     "lib/conversions.rb",
     "lib/conversions/active_record_accessors.rb",
     "lib/conversions/defaults.rb",
     "lib/conversions/unit.rb",
     "rails/init.rb",
     "test/accessor_test.rb",
     "test/conversions_test.rb",
     "test/ext_test.rb",
     "test/test_helper.rb",
     "test/unit_test.rb"
  ]
  s.homepage = %q{http://github.com/Fingertips/conversions/tree/master}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Ruby on Rails plugin that adds conversion capabilities to numeric objects"}
  s.test_files = [
    "test/accessor_test.rb",
     "test/conversions_test.rb",
     "test/ext_test.rb",
     "test/test_helper.rb",
     "test/unit_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
