# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "conversions"
  s.version = "1.4.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Manfred Stienstra", "Seamus Abshere"]
  s.date = "2012-01-17"
  s.description = "A Ruby on Rails plugin that adds conversion capabilities to numeric objects"
  s.email = "seamus@abshere.net"
  s.extra_rdoc_files = [
    "LICENSE",
    "README",
    "TODO"
  ]
  s.files = [
    "LICENSE",
    "README",
    "Rakefile",
    "TODO",
    "VERSION.yml",
    "conversions.gemspec",
    "lib/conversions.rb",
    "lib/conversions/active_record_accessors.rb",
    "lib/conversions/defaults.rb",
    "lib/conversions/unit.rb",
    "test/accessor_test.rb",
    "test/conversions_test.rb",
    "test/ext_test.rb",
    "test/test_helper.rb",
    "test/unit_test.rb"
  ]
  s.homepage = "http://github.com/seamusabshere/conversions"
  s.rdoc_options = ["--line-numbers", "--inline-source"]
  s.require_paths = ["lib"]
  s.rubyforge_project = "conversions"
  s.rubygems_version = "1.8.10"
  s.summary = "A Ruby on Rails plugin that adds conversion capabilities to numeric objects"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.4"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.4"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.4"])
  end
end

